name: Update README Stats
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Optionally rebuild README sections here."
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update README (auto)" || echo "No changes"
          git push || true