name: Update Recent Blog Posts

on:
  schedule:
    - cron: '0 */6 * * *'   # Runs every 6 hours (UTC)
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install feedparser

      - name: Update README with recent posts
        run: python .github/scripts/update_posts_to_readme.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "chore: update recent blog posts"
          git push
